# Generated by Django 4.2.7 on 2023-12-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingAPI',
        ),
        migrations.DeleteModel(
            name='MenuAPI',
        ),
    ]
