# Generated by Django 4.2.7 on 2023-12-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuapi',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
